sudo: true
language: node_js
node_js:
  - "node"
cache: yarn
env:
  global:
    - AWS_DEFAULT_REGION=eu-central-1
install:
  - sudo apt-get install python2.7
  - curl -O https://bootstrap.pypa.io/get-pip.py
  - sudo python27 get-pip.py
  - pip install awscli
script:
  - aws s3 sync www s3://learning-static-hosting --delete
