language: python
python:
  - "3.5"
cache: pip
env:
  - AWS_ACCESS_KEY_ID=YOUR_AWS_ACCESS_KEY
  - AWS_SECRET_ACCESS_KEY=YOUR_AWS_SECRET_KEY
  - AWS_DEFAULT_REGION=eu-central-1
install:
  - pip install awscli
script:
  - aws s3 sync www s3://learning-static-hosting --delete
