language: python
python:
  - "3.5"
cache: pip
install:
  - pip install awscli
script:
  - echo 'We dont have to do anything yet'
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: "learning-static-hosting"
  skip_cleanup: true
  region: eu-west-1
  local_dir: www
